version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-name: electron
      - dependency-name: electron-builder
    open-pull-requests-limit: 2
